name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
          
      - name: Install and Build
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "lts/*"
          cache: "yarn"
          
      - name: Cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-


      - name: Build
        run: |
          npm i
          npm run build
          npm run export
      
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws s3 sync ./out s3:/${{ github.event.repository.name }}/ --acl bucket-owner-full-control
