name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3
          
      - name: Install and Build
        uses: actions/setup-node@3
        with:
          node-version: "lts/*"
          cache: "yarn"
          
      - name: Cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-


      - name: Build
        run: |
          npm i
          npm run build
          npm run export
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./out
