name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
          
      - name: Install and Build
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Build
        run: |
          npm i
          npm run build
          npm run export
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./out
